version: '2'

services:
    db:
        image: mysql
        volumes:
            - ./temp/dev/data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: symfony
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: php/dev
        volumes:
            - ./symfony:/var/www/html
            - ./temp/dev/logs:/var/www/html/app/logs
            - ./temp/dev/cache:/var/www/html/app/cache
        environment:
            XDEBUG_CONFIG: remote_host=172.16.239.1
        extra_hosts:
            - 'hostmachine: 172.16.239.1'
    nginx:
        build: nginx/dev
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./temp/dev/nginx/logs:/var/log/nginx
        extra_hosts:
            - 'hostmachine: 172.16.239.1'
    redis:
        build: redis
        volumes:
          - ./temp/dev/data/redis:/data
        ports:
            - 172.16.239.1:6379:6379
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.1
